# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:

- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.7'
    addToPath: true
    architecture: 'x64'

- task: CmdLine@2
  inputs:
    script: |
      python -m pip install --upgrade pip
      
      pip install -r requirements.txt
      
      displayName: 'Install dependencies'

- script: |
      pytest tests/ --junitxml=/reports/crael-test-report.xml
      displayName: 'Run tests'


- task: PublishTestResults@2
  inputs:
    testResultsFormat: 'JUnit'
    testResultsFiles: '/reports/crael-test-result.xml'
    mergeTestResults: true
    testRunTitle: 'Crael Unit Tests'